USE spring-orders;

INSERT INTO orders
(VR_PEDIDO, STATUS)
VALUES
('15.50', 'CREATED');

INSERT INTO orders
(VR_PEDIDO, STATUS)
VALUES
('17.30', 'COMPLETED');

INSERT INTO orders
(VR_PEDIDO, STATUS)
VALUES
('17.30', 'INCOMPLETE');

INSERT INTO orders
(VR_PEDIDO, STATUS)
VALUES
('17.30', 'ABANDONED');